### ISSUE TITLE
Thefuck seems to not be working correctly

### ISSUE THREAD

**Issue by ifosch** [ifosch/eos-setup#11]
```
❯ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 53, in main
    fix_command(known_args)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 35, in fix_comma
nd                                                                                   
    selected_command = select_command(corrected_commands)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/ui.py", line 81, in select_comm
and                                                                                  
    logs.confirm_text(selector.value)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/logs.py", line 72, in confirm_t
ext                                                                                  
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not
 in range(128)                                                                       
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

**Comment by ifosch** [comment]
This looks ok now.
